# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-SimpleObject-LibXML
version:      0.60
version_from: LibXML.pm
installdirs:  site
requires:
    XML::LibXML:                   XML::LibXML::Common

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
